apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oi50sfo2j-python 
  janus-idp.io/tekton: oi50sfo2j-python
  backstage.io/kubernetes-id: oi50sfo2j-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oi50sfo2j-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  